name: Build # and Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: target/release/hotspot-drop*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Produce output
        run: |
          mkdir output
          for dir in build-*
          do
            for file in $dir/hotspot-drop*
            do
              mv $dir/$file output/$dir_$file
            done
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: new release yay
          files: output/*
